sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip wheel setuptools
  - pip install coveralls codacy-coverage tox-travis

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/alexandriadocs

script:
  - tox

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
